name: "Deploy react app to GitHub Pages"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build
        run: |
          npm install
          PUBLIC_URL=https://dee.codes/gym-booking npm run build
      - name: Deploy
        run: |
          git config --global user.name 'GitHub Actions'
          git config user.email github-actions@github.com
          git checkout -b gh-pages
          git --work-tree build add --all
          git commit -m 'Deploy'
          git push -f origin gh-pages
